wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: train_loss
      6:
      - 3
      7:
      - 1
    - 1: train_score
      6:
      - 3
      7:
      - 2
    - 1: val_score
      6:
      - 3
      7:
      - 2
    python_version: 3.8.10
    start_time: 1644483591
    t:
      1:
      - 2
      - 3
      - 12
      2:
      - 2
      - 3
      - 12
      3:
      - 7
      4: 3.8.10
      5: 0.12.10
      8:
      - 5
